export const COMPONENT_TYPES = {
  SUPPLY: 'SUPPLY',
  METER: 'METER',
  MCB: 'MCB',
  SOCKET: 'SOCKET',
  NEUTRAL_BAR: 'NEUTRAL_BAR',
  EARTH_BAR: 'EARTH_BAR',
  BUSBAR: 'BUSBAR',
  SWITCH: 'SWITCH',
  LAMP: 'LAMP',
  GENERIC_LOAD: 'GENERIC_LOAD',
  FAN: 'FAN',
  AC: 'AC',
  HEATER: 'HEATER',
  GEYSER: 'GEYSER',
  RCCB: 'RCCB',
  RCBO: 'RCBO',
  FAULT_SHORT_LN: 'FAULT_SHORT_LN',
  FAULT_LEAK_LE: 'FAULT_LEAK_LE',
  HUMAN_BODY: 'HUMAN_BODY',
  JUNCTION_BOX: 'JUNCTION_BOX',
  INVERTER: 'INVERTER',
  CHANGEOVER: 'CHANGEOVER',
};

export const TERMINAL_KINDS = {
  PHASE: 'PHASE',
  NEUTRAL: 'NEUTRAL',
  EARTH: 'EARTH',
  GENERIC: 'GENERIC',
};

export const LOAD_TYPES = {
  RESISTIVE: 'RESISTIVE',
  INDUCTIVE: 'INDUCTIVE',
  CAPACITIVE: 'CAPACITIVE',
};