export const COMPONENT_TYPES = {
  SUPPLY: 'SUPPLY',
  METER: 'METER',
  MCB: 'MCB',
  SOCKET: 'SOCKET',
  NEUTRAL_BAR: 'NEUTRAL_BAR',
  EARTH_BAR: 'EARTH_BAR',
  BUSBAR: 'BUSBAR',
  SWITCH: 'SWITCH',
  LAMP: 'LAMP',
  RCCB: 'RCCB',
  RCBO: 'RCBO',
};

export const TERMINAL_KINDS = {
  PHASE: 'PHASE',
  NEUTRAL: 'NEUTRAL',
  EARTH: 'EARTH',
  GENERIC: 'GENERIC',
};
