export const COMPONENT_TYPES = {
  SUPPLY: 'SUPPLY',
  MCB: 'MCB',
  SOCKET: 'SOCKET',
};

export const TERMINAL_KINDS = {
  PHASE: 'PHASE',
  NEUTRAL: 'NEUTRAL',
  EARTH: 'EARTH',
  GENERIC: 'GENERIC',
};
